name: publish

on:
  push:
    branches: ["main"]

jobs:
  create-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN_CD }}
      - name: Build image
        run: |
          docker build . --tag ghcr.io/JDPedroza/restapi-node-docker:latest
          docker push ghcr.io/JDPedroza/restapi-node-docker:latest

  deploy:
    needs: create-docker-image
    runs-on: ubuntu-latest
    steps:
      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: SSH into server
        run: |
          sshpass -p ${{ secrets.AUTH_PASS }} ssh -o StrictHostKeyChecking=no ${{ secrets.AUTH_SERVER }} << EOF
            cd restapi-node/
            docker login ghcr.io -u JDPedroza -p ${{ secrets.TOKEN_CD }}
            docker pull ghcr.io/JDPedroza/restapi-node-docker:latest
            docker stop restapinode || true
            docker rm restapinode || true
            docker run -d -p 4000:3000 --name restapinode ghcr.io/JDPedroza/restapi-node-docker:latest
          EOF
