name: publish

on:
  push:
    branches: ["main"]

jobs:
  create-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN_GITHUB }}
      - name: Build image
        run: |
          docker build . --tag ghcr.io/jdpedroza/restapi-node-docker:latest
          docker push ghcr.io/jdpedroza/restapi-node-docker:latest

  deploy:
    needs: create-docker-image
    runs-on: ubuntu-latest
    steps:
      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: SSH into server
        run: |
          TEMP_KEY_FILE=$(mktemp)
          echo "${{ secrets.PRIVATE_KEY }}" > $TEMP_KEY_FILE
          chmod 600 $TEMP_KEY_FILE
          TEMP_DOCKER_PASS=$(mktemp)
          echo "${{ secrets.TOKEN_GITHUB }}" > $TEMP_DOCKER_PASS
          chmod 600 $TEMP_DOCKER_PASS
          sshpass ssh -o StrictHostKeyChecking=no -i $TEMP_KEY_FILE ${{ secrets.AUTH_SERVER }} "cd restapi-node/ && cat $TEMP_DOCKER_PASS | sudo docker login ghcr.io -u JDPedroza --password-stdin && sudo docker pull ghcr.io/jdpedroza/restapi-node-docker:latest && sudo docker stop restapinode || true && sudo docker rm restapinode || true && sudo docker run -d -p 4000:3000 --name restapinode ghcr.io/jdpedroza/restapi-node-docker:latest"
          rm -f $TEMP_KEY_FILE $TEMP_DOCKER_PASS
